name: Build, Push and Run Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Check out code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23 # Specify your Node.js version

      # Restore Node.js dependencies from cache
      - name: Restore cache for Node.js
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/coder-vippro/betterchatgpt-plus-1.17.0:latest
            ghcr.io/coder-vippro/betterchatgpt-plus-1.17.0:${{ github.sha }}

  run_container:
    runs-on: self-hosted
    needs: build_and_push
    steps:
      # Pull image from GHCR
      - name: Pull Docker image
        run: docker pull ghcr.io/coder-vippro/betterchatgpt-plus-1.17.0:latest

      # Run container from pulled image
      - name: Run Docker container
        run: |
          docker stop my_container || true
          docker rm my_container || true
          docker run -d --name my_container ghcr.io/coder-vippro/betterchatgpt-plus-1.17.0:latest
